### ISSUE TITLE
An uncaught Exception was encountered

### ISSUE THREAD

**Issue by prashantnirgun** [gitdk1/CI3-HMVC-IonAuth#1]
Unable to locate the model you have specified: Ion_auth_model
Filename: /var/www/html/setu.local/public_html/system/core/Loader.php
Line Number: 344

**Comment by gitdk1** [comment]
If you running it in one of the Linux OSs it could be the capitalization of the letters. I will have a look at it now.

**Comment by gitdk1** [comment]
Try capitalizing [ion_auth_model.php > **Ion_auth_model.php**] in **application\modules\users\models**
Let me know if that solves your issue.

**Comment by prashantnirgun** [comment]
Thanks It works. I am very sorry I just forgot to check that. Thanks I am closing the ticket
