### ISSUE TITLE
CI_Controller classes give error Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by prashantnirgun** [gitdk1/CI3-HMVC-IonAuth#2]
I implemented HMVC everything works fine but if we called welcome class which has CI_Controller as base class give the following error.

Unable to locate the specified class: Session.php

I added session library in autoload.php set Encryption key also. If we called any inherit from any classes it works fine but for CI_Controller it give error.

**Comment by gitdk1** [comment]
Please try using `class Xyz extends MX_Controller`. That's the way HMVC works to extend MVC. Let me know if that solves your issue.

**Comment by prashantnirgun** [comment]
problem is with class Auth extends CI_Controller {} its giving error

**Comment by prashantnirgun** [comment]
OK if I change it to
class Auth extends MX_Controller {---}  
It works.

**Comment by gitdk1** [comment]
That's great. I was just about to test it. I will update the repository.

**Comment by prashantnirgun** [comment]
Thanks I will close the ticket

**Comment by prashantnirgun** [comment]
A PHP Error was encountered
Severity: Notice
Message: Undefined property: CI::$data
Filename: MX/Controller.php
Line Number: 59
Backtrace:
File: /var/www/html/setu.local/public_html/application/third_party/MX/Controller.php
Line: 59
Function: _error_handler
File: /var/www/html/setu.local/public_html/application/modules/users/controllers/Auth.php
Line: 50
Function: __get
File: /var/www/html/setu.local/public_html/index.php
Line: 292
Function: require_once

**Comment by gitdk1** [comment]
Please add on line 15: [](https://github.com/gitdk1/CI3-HMVC-IonAuth/blob/master/application/modules/users/controllers/Auth.php#L15)

**Comment by prashantnirgun** [comment]
Cool

**Comment by gitdk1** [comment]
Please re-download the file. Tested all Ion Auth pages. 

https://github.com/gitdk1/CI3-HMVC-IonAuth/blob/master/application/modules/users/controllers/Auth.php

**Comment by prashantnirgun** [comment]
after successful login it send to http://localhost/users/auth/index.html ?
I tried to put echo but can't caught where its calling index.html ?

**Comment by gitdk1** [comment]
It doesn't. It's either .htaccess that you have or virtual host configuration.

**Comment by prashantnirgun** [comment]
can you figure out any thing wrong in it

Options +FollowSymLinks
Options -Indexes
DirectoryIndex index.php
RewriteEngine on
RewriteCond $1 !^(index\.php|images|robots\.txt)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L,QSA]

**Comment by prashantnirgun** [comment]
yes I do have virtual host I will it make any difference (setu.local) ? What is the solution for it?

**Comment by gitdk1** [comment]
.htaccess rewrite works fine. Make sure that you don't have any rewrite rules in the virtual host to index.html. If you do, remove it and reload web server.

**Comment by prashantnirgun** [comment]
no such entry found

<VirtualHost *:80>
	ServerAdmin webmaster@test.com
	DocumentRoot /var/www/html/setu.local/public_html

	ServerName setu.local
	ServerAlias www.setu.local

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by gitdk1** [comment]
Nope, there's nothing wrong there either, but from what I can tell is it's not CodeIgniter issue.

- [ ] See what it does without .htaccess
- [ ] Check server requirements: https://www.codeigniter.com/user_guide/general/requirements.html

**Comment by prashantnirgun** [comment]
have you tried with fresh installer at your side as I tried on Ubuntu 15 and Windows 7 both facing problem.

**Comment by prashantnirgun** [comment]
ok I downloaded the code and found its working I am closing the issue.
