### ISSUE TITLE
creating https over http on localhost

### ISSUE THREAD

**Issue by prashantnirgun** [gitdk1/CI3-HMVC-IonAuth#3]
Hi

if i tried to login using url localhost/ci/index.php/users/auth/login it redirect to 
https://localhost/ci/index.php/users/auth/login I removed .htaccess file. How to redirect it to http 
my $config['base_url'] = 'http://localhost/ci';

prblem area is if the images, jquery and other resources are not loaded everything gets failed because browser console shows the following error.

Mixed Content: The page at 'https://localhost/ci/index.php/users/auth/login' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://localhost/ci/index.php/users/auth/login'. This endpoint should be made available over a secure connection.

**Comment by gitdk1** [comment]
It doesn't redirect between http and https on its own. It all depends on your preference. The error is quite clear, if you want to use https, your form 'action' must point to https. If not make sure it's not there. It's the way Ion Auth is set up. If you consider that an issue, it should be reported to https://github.com/benedmunds/CodeIgniter-Ion-Auth

**Comment by prashantnirgun** [comment]
Where it is mention to use https ? Is it in any configuration file ? I checked out the view its 
<?php echo form_open("users/auth/login");?>. Do you where do I mentioned my preference?

Thanks in advance

**Comment by gitdk1** [comment]
If you want to use https permanently, change base_url to http**s**://localhost/ci. 

If you don't know how CodeIgniter manages URLs make sure to read
http://www.codeigniter.com/user_guide/helpers/url_helper.html

This is repository offering solution to HMVC with Ion Auth, so for any other modifications are entirely on your own to research and get help on forums.

**Comment by prashantnirgun** [comment]
No I need http but it automatically turns it into https how do i stop doing this ?

**Comment by gitdk1** [comment]
It's not codeigniter doing that. If it does, then it's your modifications that are influencing it. Inspect the login page when loaded in a browser and check if form action is pointing to http or https. If https, then rewrite form action with base_url ('users/auth/login');

**Comment by prashantnirgun** [comment]
Just in case I downloaded the current version 3.0.4. can you tell me which version you are using as only difference is the system folder which i am adding. I suspect could be the reason. my url was
http://localhost/ci/index.php/users/auth/login and I had not tampered any view or controller. Its a fresh installation. If in case you are using some different just do favor zip it and mail me on info@tss.net.in

**Comment by gitdk1** [comment]
I'm using the one that is here. It's version 3.0.4.

**Comment by prashantnirgun** [comment]
do one favor zip applicaiotn,system, index.php, .htaccess and share it

**Comment by prashantnirgun** [comment]
PHP Version 5.4.31

**Comment by prashantnirgun** [comment]
can you check your phpinfo() Configuration / apache2handler :
Apache Version : Apache/2.4.10 (Win32) OpenSSL/1.0.1h PHP/5.4.31

Is this making any mistake whats was on your side ?

**Comment by gitdk1** [comment]
Get php 7.0.3.

**Comment by prashantnirgun** [comment]
Ok I removed the OpenSSL now its stop converting http to https. Everything get sorted out. I was using xamp remove OpenSSl now everything is stable. Thanks. Today I can sleep without tension. Once again thanks. I will close the ticket in morning checking on my Ubuntu laptop/

**Comment by prashantnirgun** [comment]
Its work on Ubuntu thanks
